### ISSUE TITLE
Outdated team listing page

### ISSUE THREAD

**Issue by sciwhiz12** [QuiltMC/quiltmc.org#116]
There are a few discrepancies between the [official team listing page](https://quiltmc.org/en/about/teams/) and the actual teams as can be seen through Discord:

- @tempest15 is still included as a Moderator; she became a Community Manager on March 6, 2023.
- @TibiNonEst is not yet included as a Moderator; they graduated from trainee status on March 9, 2023.
- @FoundationGames, a Chasm developer per the `Team: Chasm` role on the Discord server, has neither team data (per `TeamData.js`) nor included as a Chasm developer.
- @Geolykt is no longer in the Tooling or Community servers, and seems to not be in the organization (at least from the perspective of a non-member). They are currently included as a Decompilers team member.
- @TheGlitch76 and @ix0rai are not yet included as Quilted Fabric API members; they have the `Team: QFAPI` role on the Discord server.
- @Oliver-makes-code and @Akarys42 are included in the Events Team on the page but they do not have the `Events Team` role on the (community) Discord server.
- The Update Leader role on the Discord server has no equivalent listing on the page.

The Update Leader role and the note for FoundationGames were brought up in #92, which has still gone unmerged.

**Comment by Geolykt** [comment]
> * @Geolykt [...] seems to not be in the organization (at least from the perspective of a non-member).

This is indeed correct.

**Comment by tempest15** [comment]
Your mention for starchild is incorrect, their account is @Akarys42

**Comment by Southpaw1496** [comment]
My PR (#118) has so far removed Geo, added Tempest to the Community Managers, and added Tibs to Moderators. I haven't yet removed her from Moderators, since they're now more separate roles than they were when the page was created, so I think we should go the other way and add Gdude, Apple, Mango, and Leah to the Moderators again. 

Glitch and Rai's QSL additions will be handled by #112  , and the Update Leaders will be added by #92.

In regards to the Events Team, that was only made its own separate role recently, so that's probably the reason for that oversight.

**Comment by Southpaw1496** [comment]
FoundationGames has now also been added

**Comment by Southpaw1496** [comment]
Looks like we've *all* been superseded by Akarys 🙃

**Comment by Akarys42** [comment]
> Looks like we've _all_ been superseded by Akarys 🙃

Actually, not really. There are still a few issues, although most stem from broken Github teams. We should merge #117 and then evaluate what still needs changing.
