### ISSUE TITLE
Upgrade to Node 18/19, also upgrade Astro if possible

### ISSUE THREAD

**Issue by Southpaw1496** [QuiltMC/quiltmc.org#119]
Thanks to #115, we can now use modern Node versions without Cloudflare having a heart attack, so we should upgrade. 18 is the LTS version, but I see no reason why we shouldn't upgrade to 19 if we can.

We should also upgrade to Astro 2.x if our extensions support it.

**Comment by pluiedev** [comment]
Upgrading Node is easy but if we were to upgrade to Astro 2.x, I'd like to make use of [content collections](https://docs.astro.build/en/guides/content-collections/) since they provide a much better way to view and organize pages, which would cut down on a lot of wacky uses of `Astro.glob` in the codebase. However it looks quite complex and I don't really have spoons for that, but if anyone wants to tackle that then go ahead :purple_heart:

**Comment by Southpaw1496** [comment]
Is there any reason not to upgrade to Node 19?

**Comment by pluiedev** [comment]
> Is there any reason not to upgrade to Node 19?

Can't think of any
