### ISSUE TITLE
all pages say they were edited on the same date

### ISSUE THREAD

**Issue by ix0rai** [QuiltMC/quiltmc.org#160]
examples:
![image](https://github.com/QuiltMC/quiltmc.org/assets/66223394/a90ddf12-de17-479e-b750-e3abe81fa26a)
![image](https://github.com/QuiltMC/quiltmc.org/assets/66223394/57d13b61-5e2c-44c6-aa57-fcdf9eedef7a)
![image](https://github.com/QuiltMC/quiltmc.org/assets/66223394/9d7c526a-9c0f-40c3-ab41-67b2685e47ee)

this is. well. incorrect
nothing else to say

**Comment by obj-obj** [comment]
Yeah I'm pretty sure it just uses the date of the latest git commit instead of the time that specific page was edited

**Comment by Akarys42** [comment]
It is because the workflow is now using upstream checkout action for some reason? It doesn't unpack the git data correctly, which is why the fork was used. No idea why it was changed.

Commit responsible for this: https://github.com/QuiltMC/quiltmc.org/commit/b9428ae1ba539435f1bf9e59c766e5141076e67f

**Comment by Southpaw1496** [comment]
I changed it because I couldn't find any source code to see what it did, and I didn't like the idea of using a closed-source action in our pipeline that could change at any time.

**Comment by Southpaw1496** [comment]
I blame GitHub search
<img width="1333" alt="Screenshot of GitHub search screen with no results. src="https://github.com/QuiltMC/quiltmc.org/assets/44805409/746fc8fa-c110-4237-8e7a-532cc8f0b00d">

**Comment by Southpaw1496** [comment]
#164 should fix it
