### ISSUE TITLE
[Suggestion] Add a Forum

### ISSUE THREAD

**Issue by Drakesdrs** [QuiltMC/quiltmc.org#18]
Add an official quiltmc forum on quiltmc website.

**Comment by gdude2002** [comment]
A small update, because why not?

With Quilt's projected April beta release date, I've been trying out different forum software. I think it'll probably be Discourse, after some testing of modern forum platforms.

Here's an early preview, because why not?

![image](https://user-images.githubusercontent.com/204153/156878755-630e619f-1f0e-4d9a-9f5b-0d2613014547.png)

**Comment by Southpaw1496** [comment]
This has now been added! See [the announcement post](https://quiltmc.org/blog/2022/05/07/announcing-quilt-forum/) and https://forum.quiltmc.org
