### ISSUE TITLE
MC patch note weirdness leading to versions not being found

### ISSUE THREAD

**Issue by anonymous123-code** [QuiltMC/quiltmc.org#215]
When loading the patch patch notes from: https://quiltmc.org/en/mc-patchnotes/#24w18a, something inserts a slash, changing the url to the patch notes for that update not being displayed. When using the UI to change to the correct URL, reloading once inserts the slash, and reloading a second time removes the content.
Tested on firefox

**Comment by TheEpicBlock** [comment]
The issue is in [this](<https://github.com/QuiltMC/quiltmc.org/blob/87c465c3de756c9baa1f2099c9bfba21456123dd/src/pages/api.astro#L11-L15>) code. It gets loaded globally when it shouldn't. See also the conversation on discord [here](<https://discord.com/channels/817576132726620200/1103986836415713300/1236075472719446056>)
