### ISSUE TITLE
New launcher: BakaXL

### ISSUE THREAD

**Issue by EldersJavas** [QuiltMC/quiltmc.org#51]
Hello Quilt Team,

I loved Quilt Loader and I found one of a third-party Minecraft Launcher "[BakaXL](https://www.bakaxl.com/)" that I used mostly has support Quilt installation as soon as they hear Quilt project.

So after asking their developers, I would like to recommend Quilt Homepage and Docs add "[BakaXL](https://www.bakaxl.com/)" as one of the third-party Minecraft Launcher that support Quilt.

They have currently working on English support for their website, but English localization has already finished inside Launcher itself.

Anyway, If you allowed, I'll write the tutorial as fast.

Regards.

![image](https://user-images.githubusercontent.com/55266266/172787616-a68f3fb1-dfd0-41e5-822c-d52d9e43722a.png)

**Comment by gdude2002** [comment]
Hello! Sorry for the delay!

The list of launchers on the site are known to be safe, and are very popular in the western Minecraft modding community. We do need to be careful what launchers we add to the site and, while the launcher you linked does look nice, we don't have anyone on the team that both speaks Chinese and is qualified to audit an unfamiliar launcher.

While we appreciate why this can be frustrating, we'd prefer to be careful -- none of us are familiar with this launcher or the communities where it's used, so we can't vouch for its safety.

Still, thanks for the issue regardless!

**Comment by EldersJavas** [comment]
Got it, thank you!

**Comment by Big-Cake-jpg** [comment]
Excuse me. In fact, BakaXL has a fully functioning i18n system powered by the community, not only in Chinese. [Repo is here.](https://github.com/BakaXL- Launcher/BakaXL)

**Comment by gdude2002** [comment]
Apologies for getting to this so late.

> by the way, Will i18N be added to the website?

I'd like to, but I honestly have no idea where to begin with that. If you have any ideas, feel free to open a new issue.

> Excuse me. In fact, BakaXL has a fully functioning i18n system powered by the community, not only in Chinese.

That doesn't really change anything - we don't have any trusted users making use of your launcher, and it would be risky for us to recommend a piece of software we're not familiar with. Ultimately, users trust us not to link to software we don't explicitly trust, so it's very unlikely a launcher that's newer or unknown in the West will be added to the site.

The most I can do is to ask @LeoCTH to look into it for now.

**Comment by TT702** [comment]
Hi, I am the author of the BakaXL Launcher.

Protecting the player who has purchased a legit copy of Minecraft is one of the core principles of our design.

Back when BakaXL was in the planning stage, we designed a copyright protection system preventing players outside of the China Administration zone from being able to launch Minecraft without purchasing a legit copy. (The partnership between NetEase and Microsoft/Mojang Studio allows players in China to enjoy Minecraft: Java Edition and Bedrock Edition for free.)

So, how does this system work? BakaXL Launcher simply does not allow users who are physically in America, Europe, or any country/region in the world where the "DMCA Act." is in effect.
BakaXL Launcher will not provide the option to launch Minecraft with offline authentication to users described above.

But just like Official Minecraft Launcher or MultiMC, in order to use offline authentication, users must have previously logged into their Mojang account or Microsoft account that has a valid copy of Minecraft.

I believe that @leocth might not take a closer look or perform any research before making that comments, which is unprofessional, and makes the result frustrating.

BakaXL was aims to become the bridge between western and eastern Minecraft modding communities. We have always been listening to the suggestions and requests from our users, providing localization and many exciting features such as CurseForge/Modrinth support, Virtual LAN Game, Disable Minecraft Chat Report without modding the game, and becoming the first Minecraft launcher in China that fully supports Quilt Loader.

Without detailly knowing of BakaXL and its features, curtly making those comments and drawing the above conclusions, may adversely affect the communication between Minecraft's eastern and western community groups and lead to division and bias, which I believe is inappropriate.

That's all I want to say.
Best Regards.

----

各位好，我是 BakaXL 的作者，

在 BakaXL 的设计之初，我们将保护所有拥有合法正版 Minecraft 副本的玩家作为我们的基本设计原则之一。

在我们最初设计 BakaXL 的功能集时，我们就专门为在中国行政区以外的玩家设计了一个版权保护系统。
（由于网易与微软及Mojang Studio的合作关系，位于中国的玩家可以免费游玩 Minecraft Java 与 基岩版本）

BakaXL 的版权保护系统是如何工作的呢？很简单，BakaXL 根本就不会允许身在美国、欧洲或实际上任何可以收到“DMCA 法案”管辖的行政区域（国家/地区）内允许用户通过离线验证模式启动 Minecraft。
BakaXL 也不会向上述国家/地区的用户提供无条件的通过离线验证模式启动 Minecraft 的功能，除非他们像官方 Minecraft 启动器 或者 MultiMC 一样使用了拥有有效 Minecraft 副本的 Mojang 或者 Microsoft 账户登录。

我相信 @leocth 可能在发表相关评论之前没有对 BakaXL 进行详细的查看或者了解过相关功能在不同行政区域时如何工作，这显然非常的令人沮丧，而且很不专业。

BakaXL 一直致力于成为东西方 Minecraft 社区群体之间的桥梁，我们不断的接受来自用户的功能提案，为 BakaXL 提供了丰富的本地化以及许多令人兴奋的功能。例如针对 CurseForge 和 Modrinth 平台的支持、通过广域网与好友进行虚拟本地局域网游戏、在不修改 Minecraft 本体的情况下禁用 Minecraft 聊天追踪与举报，以及成为了全中国首个完全支持 Quilt Loader 的 Minecraft 启动器。

在得出以上结论之前，如果没有详细了解 BakaXL 及其功能，则枉然推断出的结论和造成的后果恐怕会对 Minecraft 东西方社区群体之间的交流产生不利影响，并且导致分裂和偏见，我认为这是不合适的。

以上就是我想说的。
多谢。祝好。

**Comment by Restent** [comment]
I suggest to open BakaXL and try to launch Minecraft with offline-mode in American / Europe / Anywhere that can receive the DMCA Act.

> 没有证据的说辞，什么也无法造就。

**Comment by Big-Cake-jpg** [comment]
If you said it's piracy or it's insecure without any testing or proof, you said nothing. 

> No investigation, no voice.

**Comment by gdude2002** [comment]
Disagreeing with a result is not a good reason to dogpile our issue tracker.

I'll unlock this once we've had time to look into this further.

**Comment by gdude2002** [comment]
I was contacted directly on Discord by the person that originally submitted this issue, and they've asked that this issue be deleted.

Because of the nature of GitHub issues, removing the issue doesn't really serve any purpose other than trying to hide what happened. This would just result in one of us approaching the subject again without the context within the issue - which will waste time and cause further problems.

While the author has retracted their interest in having BakaXL added to the site, we weren't done here, and this issue being abandoned by the author doesn't mean that we won't look into BakaXL again and add it to the site later on, if our research deems it to be a good idea.

Regardless, we appreciate everyone's interest on seeing this happen - I've been thinking about users from other cultures recently, so we may end up figuring something out further down the line.

**Comment by gdude2002** [comment]
Hello! It's me again.

Last night, a few of us (including Leo) downloaded and set up copies of BakaXL on
our own computers to figure out what precisely the launcher was capable of. We 
felt that it wouldn't be fair to leave this issue unaddressed, so we wanted to let 
you know what our thoughts were.

1. We were wrong about the authentication situation - it is indeed true that BakaXL
   will not let you play in offline mode without logging into a Microsoft or Mojang
   account. It turned out that Leo had gotten this impression from YouTube videos, 
   which didn't provide all of the required context. This is because Leo runs
   Linux, which BakaXL doesn't seem to support. Sorry for the mix-up!

2. The "Third-Party Authentication" option is still considered problematic for 
   people in the West, as it effectively still allows people to play Minecraft
   without paying for it. However, we understand why the option exists, and the
   benefits that it provides for players in China, who would otherwise regularly
   have to deal with connectivity problems - given that Mojang's authentication
   servers often don't work properly in China.

   We found that this option was available to users in Europe, but we were unable
   to get it working - so we assume that you're still working on the UI for this.

3. We want to point out that we're aware of the cultural differences between our
   countries and communities, and we're also aware that a launcher like BakaXL is
   likely to suffer from discoverability issues without the support of some central
   authority. However, we're not sure that listing BakaXL on a site with a
   primarily Western audience will help your project much.
   
   Instead of simply listing the launcher on our site with English instructions,
   for an English-speaking audience, we want to commit to a more sustainable
   approach to supporting our international users. This approach would involve
   fully translating the site, and maybe providing different recommendations
   depending on the language you're using. However, we're not quite sure what
   the best way for us to achieve this is just yet.

4. We also want to say that we think you've done a fantastic job with the UI work
   and, while there are clearly still some bugs, it looks far nicer than anything
   we usually work with here in the West.

All of this puts us in a rather interesting position. Ultimately, as a Western
project, we can't get away with promoting a tool to Western users that circumvents
Mojang's authentication services outside of China - Quilt must continue to operate
as a legitimate project in the eyes of the West, and failing to do so would be
somewhat suicidal for our project.

Despite this, we want to commit to supporting the Chinese Minecraft community (and
other international Minecraft communities) to the best of our ability, and to the
fullest extent that's reasonable for a Western project. As I mentioned earlier, we
think that starting with figuring out a good way to fully translate the site is a
better thing to start with, so that's what we're going to look at first.

I've unlocked the issue, so while we're looking into this, feel free to leave any
comments you might have, or any ideas you have about how best to move forward with
this plan. If you'd rather not then that's fine too - thanks for spending so much
time on this and trying so hard to work with us!

---

As I mentioned, we've been quite impressed with BakaXL, and we think you've done a
good job with it. A few pieces of feedback that you might find useful:

* It would be best to ask the user to pick the language they want to use as early
  as possible - it took us a while to figure out how to switch to English!
* The Third-Party Authentication option (which we tested with `ely.by`) failed with
  an error, but we couldn't figure out how to find more information about the
  error, so it was difficult to say whether this feature being available in Europe
  was intentional.
* The grid on the Start page is hidden until you click the profile icon at the
  lower left of the screen. Clicking on "Login" in this menu makes the grid appear,
  but doesn't bring the user to a login screen. We found that a little confusing!

**Comment by Big-Cake-jpg** [comment]
Thanks for your response! Although I'm only a user of BakaXL, I'm still happy to hear the response.

By the way,

> The grid on the Start page is hidden until you click the profile icon at the lower left of the screen. Clicking on "Login" in this menu makes the grid appear, but doesn't bring the user to a login screen. We found that a little confusing!

these grids are calling as Tiles, which is hidden by default if you didn't choose "legacy" when the launcher ask you which styling of "Start Menu" you like.

You can swipe up the bar at the lower center of the screen to get these tiles.

> My spelling and grammar may be wrong, sorry.

**Comment by bwtx2022** [comment]
> You can swipe up the bar at the lower center of the screen to get these tiles.
> 
> The bar looks like this:
> 
> ![image](https://user-images.githubusercontent.com/76810494/181908378-001f95d3-851f-4484-a2e0-50c5cab2d9a7.jpeg)

Pressing your Space on the keyboard is another way to go to Start Menu.

**Comment by bwtx2022** [comment]
> It would be best to ask the user to pick the language they want to use as early as possible - it took us a while to figure out how to switch to English!

In fact, the language option is the first option that you can see in the guide. Maybe it's not very clear, but I think developers will improve it later. 

There may be grammar issues.

**Comment by gdude2002** [comment]
It's worth noting that we tested with the stable version, not the preview builds.

**Comment by Restent** [comment]
> It's worth noting that we tested with the stable version, not the preview builds.

Many people in China like to use the parrot branch (a branch of preview build) because it's really good! 😆

**Comment by gdude2002** [comment]
That's fair, but I think most people are just going to use what the app puts in front of them, haha

**Comment by gdude2002** [comment]
As a quick update, we've been working on i18n, but have realized that Jekyll is causing us a lot of problems - we have some people rebuilding the site with a new SSG, and we'll be able to properly do i18n once that's done. For more info, see #35.

**Comment by bwtx2022** [comment]
The newest release version of BakaXL has done with the UI. 

Hope you can try it again. 

You can remove the dictionary %appdata%\BakaXL to reset the launcher.

**Comment by wifi-left** [comment]
As a user of other third-party open source launchers, I don't think offering offline logins is equivalent to piracy. Offline login allows you to play games offline when you are disconnected from the Internet. A lot of third-party launchers are also working on getting players to use the genuine version (with guides in many places, etc.).
Of course, I think we should support and try to use the genuine version for the game.
This is just my personal opinion, thanks.
(using Google Translate)
<hr/>
作为一个其他第三方开源启动器的使用者，我认为提供离线登录与盗版不相等。当你与互联网断开连接的时候，离线登录可以使您在离线状态下游玩游戏。很多第三方启动器也致力于让玩家使用正版（在很多地方有引导等）。这只是我个人的想法，谢谢。
当然，我认为我们应当支持并且尽量使用正版来进行游戏。

**Comment by gdude2002** [comment]
The issue was that BakaXL was allowing offline logins without first requiring someone to log in with a genuine account.

I've talked with one of the developers directly on Discord, and they said that this was actually a bug and that they're fixing it - so either way, there's no problem with that here now.

**Comment by gdude2002** [comment]
Hello again!

As Quilt was mentioned on Twitter about BakaXL, I realized that we still needed to finish working on this issue.

Have there been any updates to how BakaXL handles this since the last time we looked at it?

**Comment by TT702** [comment]
Hi there!

The bug that may cause "Third-party Authencation" options available before login to Microsoft Account outside Mainland China was already fixed and push to the release channel :D

The Copyright Protect Feature in BakaXL requireing the player who was not lived in Mainland China to login to their Microsoft Account before they can use both "Third-party Authencation" and "Offline" mode.

**Comment by gdude2002** [comment]
So to clarify, you've addressed all our concerns, but offline mode is still accessible in China without logging into a Microsoft account, right?

Out of curiosity, why this approach?

**Comment by Gaming32** [comment]
> The partnership between NetEase and Microsoft/Mojang Studio allows players in China to enjoy Minecraft: Java Edition and Bedrock Edition for free.

**Comment by gdude2002** [comment]
I am aware of this, but I'd like a response from someone that's part of the project - especially since I'm wondering how NetEase currently cracking down on third-party Minecraft content affects them.

**Comment by TT702** [comment]
> So to clarify, you've addressed all our concerns, but offline mode is still accessible in China without logging into a Microsoft account, right?
> 
> Out of curiosity, why this approach?

Yes, its still accessible in Mainland China.

I used to get in touch with NetEase Minecraft Dept Staffs as Third-party Minecraft Launcher Developer while back in 2016 Mojang Studios visit Shanghai ChinaJoy Expo. While asking about the future plan for Minecraft in China, they mentioned that they will provide Minecraft Java and Bedrock Edition for free to player in China.

While asking about offline mode with one of the staff in NetEase in personally, he orally said they wont forcing other launcher to login to use offline mode because they also using this feature.

I don't know that after all this years, does NetEase changes their attitude about this.

**Comment by TT702** [comment]
> I am aware of this, but I'd like a response from someone that's part of the project - especially since I'm wondering how NetEase currently cracking down on third-party Minecraft content affects them.

NetEase took down BakaXL trailer video because they thinking that in the trailer I using some game footage in China version of Minecraft and it violates the NetEase EULA ("Do not post any footage about Minecraft China Version or any related NetEase Service."). 
But in fact I did not play China version and all the footage I used was recorded by myself from my own saves, so I have no idea why they complaining.

**Comment by gdude2002** [comment]
Oh, I see, alright. In that case, I think that’s everything I need, thanks. We’ll get back to you!

**Comment by gdude2002** [comment]
[Aand we're done](https://quiltmc.org/en/install/bakaxl/). Thanks for working with us, much appreciated!

**Comment by TT702** [comment]
Thanks!
