### ISSUE TITLE
Community Methodology isn't accurate (transparency)

### ISSUE THREAD

**Issue by Milesman34** [QuiltMC/quiltmc.org#83]
Your Community Methodology is not accurate. It says "To act with transparency where possible and reasonable without trying to hide our actions, and explaining moderation decisions when asked about them", yet I was banned from your Discord without saying anything and without being notified of any ban reason. This is certainly the behavior of a "transparent system", no? And I was never sent a ModMail link either for appeals.

**Comment by gdude2002** [comment]
Generally speaking, during the server applications process, we do occasionally do non-DMing bans when the offending content found is offensive enough that forcing the staff to deal with it later -- and it's worth noting the team does have a couple minors on it that should be protected from dealing with some types of content -- would cause a significant hit to the staff team's mental health.

I have done a quick review of why you were banned, and since you're so curious, I'll post the reason here: As part of the application review process, we discovered that you are a supporter, promoter and consumer of lolicon content (porn and other NSFW drawn content involving girls that are below the age of consent, often pre-teen). 

As this content violates every reasonable Terms of Service and shows that any members of our community that happen to be minors would likely be unsafe around you, you have been banned. We will not allow you to appeal this ban.

Regardless, thanks for getting in contact, I guess.
